function G = autotuned_gains()
%AUTOTUNED_GAINS Simulation-optimized Aerosonde autopilot gains.
% Generated by tuning/autotune_all.m using the nonlinear model.

G.generated = true;
G.accepted = true;
G.roll.Kp = 2.12969467796;
G.roll.Ki = 0.104101276085;
G.roll.Kd = 0.114410995708;

G.pitch.Kp = 1.95473303027;
G.pitch.Ki = 0.092732283195;
G.pitch.Kd = 0.250273922764;

G.course.Kp = 4.8;
G.course.Ki = 0.008;

G.altitude.Kp = 0.031148383146;
G.altitude.Ki = 0.000669447120934;

G.airspeed.Kp = 0.2784093764;
G.airspeed.Ki = 0.0454221714564;

end
