function save_autotuned_gains(P, accepted)
%SAVE_AUTOTUNED_GAINS Write the optimized profile as readable MATLAB code.

project_root = fileparts(fileparts(mfilename('fullpath')));
filename = fullfile(project_root,'tuning','autotuned_gains.m');
file_id = fopen(filename,'w');
if file_id < 0, error('Unable to write %s.',filename); end
cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id,'function G = autotuned_gains()\n');
fprintf(file_id,'%%AUTOTUNED_GAINS Simulation-optimized Aerosonde autopilot gains.\n');
fprintf(file_id,'%% Generated by tuning/autotune_all.m using the nonlinear model.\n\n');
if accepted, accepted_text = 'true'; else, accepted_text = 'false'; end
fprintf(file_id,'G.generated = true;\nG.accepted = %s;\n',accepted_text);
loops = {'roll','pitch','course','altitude','airspeed'};
for index = 1:numel(loops)
    loop_name = loops{index}; gains = P.control.(loop_name);
    fprintf(file_id,'G.%s.Kp = %.12g;\n',loop_name,gains.Kp);
    fprintf(file_id,'G.%s.Ki = %.12g;\n',loop_name,gains.Ki);
    if isfield(gains,'Kd'), fprintf(file_id,'G.%s.Kd = %.12g;\n',loop_name,gains.Kd); end
    fprintf(file_id,'\n');
end
fprintf(file_id,'end\n');
clear cleanup
clear autotuned_gains
end
